kind: Service
apiVersion: v1
metadata:
  name: harbourmaster
spec:
  type: ClusterIP
  selector:
    name: harbourmaster
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  externalIPs: 
    - A.B.C.D