apiVersion: v1
kind: Service
metadata:
  name: harbourmaster
  namespace: harbourmaster
  labels:
    name: harbourmaster
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    name: harbourmaster
  type: nodePort  
